//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalSystemApp.WinUI.AracServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AraclarDTO", Namespace="http://schemas.datacontract.org/2004/07/CarRentalSystemApp.DTO")]
    [System.SerializableAttribute()]
    public partial class AraclarDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte AirbagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float AnlikKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AracIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BagajHacmiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DurumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EhliyetYasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal GunlukKiralikFiyatiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float GunukKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalSystemApp.WinUI.AracServiceReference.KiralikBilgiDTO KiralikBilgiDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KoltukSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarkaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MinYasSiniriField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalSystemApp.WinUI.AracServiceReference.SirketDTO SirketDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SirketIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Airbag {
            get {
                return this.AirbagField;
            }
            set {
                if ((this.AirbagField.Equals(value) != true)) {
                    this.AirbagField = value;
                    this.RaisePropertyChanged("Airbag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float AnlikKm {
            get {
                return this.AnlikKmField;
            }
            set {
                if ((this.AnlikKmField.Equals(value) != true)) {
                    this.AnlikKmField = value;
                    this.RaisePropertyChanged("AnlikKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AracID {
            get {
                return this.AracIDField;
            }
            set {
                if ((this.AracIDField.Equals(value) != true)) {
                    this.AracIDField = value;
                    this.RaisePropertyChanged("AracID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BagajHacmi {
            get {
                return this.BagajHacmiField;
            }
            set {
                if ((this.BagajHacmiField.Equals(value) != true)) {
                    this.BagajHacmiField = value;
                    this.RaisePropertyChanged("BagajHacmi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Durum {
            get {
                return this.DurumField;
            }
            set {
                if ((this.DurumField.Equals(value) != true)) {
                    this.DurumField = value;
                    this.RaisePropertyChanged("Durum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EhliyetYasi {
            get {
                return this.EhliyetYasiField;
            }
            set {
                if ((this.EhliyetYasiField.Equals(value) != true)) {
                    this.EhliyetYasiField = value;
                    this.RaisePropertyChanged("EhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GunlukKiralikFiyati {
            get {
                return this.GunlukKiralikFiyatiField;
            }
            set {
                if ((this.GunlukKiralikFiyatiField.Equals(value) != true)) {
                    this.GunlukKiralikFiyatiField = value;
                    this.RaisePropertyChanged("GunlukKiralikFiyati");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float GunukKm {
            get {
                return this.GunukKmField;
            }
            set {
                if ((this.GunukKmField.Equals(value) != true)) {
                    this.GunukKmField = value;
                    this.RaisePropertyChanged("GunukKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalSystemApp.WinUI.AracServiceReference.KiralikBilgiDTO KiralikBilgiDTO {
            get {
                return this.KiralikBilgiDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.KiralikBilgiDTOField, value) != true)) {
                    this.KiralikBilgiDTOField = value;
                    this.RaisePropertyChanged("KiralikBilgiDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KoltukSayisi {
            get {
                return this.KoltukSayisiField;
            }
            set {
                if ((this.KoltukSayisiField.Equals(value) != true)) {
                    this.KoltukSayisiField = value;
                    this.RaisePropertyChanged("KoltukSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Marka {
            get {
                return this.MarkaField;
            }
            set {
                if ((object.ReferenceEquals(this.MarkaField, value) != true)) {
                    this.MarkaField = value;
                    this.RaisePropertyChanged("Marka");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinYasSiniri {
            get {
                return this.MinYasSiniriField;
            }
            set {
                if ((this.MinYasSiniriField.Equals(value) != true)) {
                    this.MinYasSiniriField = value;
                    this.RaisePropertyChanged("MinYasSiniri");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model {
            get {
                return this.ModelField;
            }
            set {
                if ((object.ReferenceEquals(this.ModelField, value) != true)) {
                    this.ModelField = value;
                    this.RaisePropertyChanged("Model");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalSystemApp.WinUI.AracServiceReference.SirketDTO SirketDTO {
            get {
                return this.SirketDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketDTOField, value) != true)) {
                    this.SirketDTOField = value;
                    this.RaisePropertyChanged("SirketDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SirketID {
            get {
                return this.SirketIDField;
            }
            set {
                if ((this.SirketIDField.Equals(value) != true)) {
                    this.SirketIDField = value;
                    this.RaisePropertyChanged("SirketID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KiralikBilgiDTO", Namespace="http://schemas.datacontract.org/2004/07/CarRentalSystemApp.DTO")]
    [System.SerializableAttribute()]
    public partial class KiralikBilgiDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AlinanUcretField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float AnlikKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AracIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO AraclarDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BaslangicTarihiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KiralikIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MusteriIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalSystemApp.WinUI.AracServiceReference.MusterilerDTO MusterilerDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float SonKmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TeslimTarihiField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AlinanUcret {
            get {
                return this.AlinanUcretField;
            }
            set {
                if ((this.AlinanUcretField.Equals(value) != true)) {
                    this.AlinanUcretField = value;
                    this.RaisePropertyChanged("AlinanUcret");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float AnlikKm {
            get {
                return this.AnlikKmField;
            }
            set {
                if ((this.AnlikKmField.Equals(value) != true)) {
                    this.AnlikKmField = value;
                    this.RaisePropertyChanged("AnlikKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AracID {
            get {
                return this.AracIDField;
            }
            set {
                if ((this.AracIDField.Equals(value) != true)) {
                    this.AracIDField = value;
                    this.RaisePropertyChanged("AracID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO AraclarDTO {
            get {
                return this.AraclarDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.AraclarDTOField, value) != true)) {
                    this.AraclarDTOField = value;
                    this.RaisePropertyChanged("AraclarDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BaslangicTarihi {
            get {
                return this.BaslangicTarihiField;
            }
            set {
                if ((this.BaslangicTarihiField.Equals(value) != true)) {
                    this.BaslangicTarihiField = value;
                    this.RaisePropertyChanged("BaslangicTarihi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KiralikID {
            get {
                return this.KiralikIDField;
            }
            set {
                if ((this.KiralikIDField.Equals(value) != true)) {
                    this.KiralikIDField = value;
                    this.RaisePropertyChanged("KiralikID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MusteriID {
            get {
                return this.MusteriIDField;
            }
            set {
                if ((this.MusteriIDField.Equals(value) != true)) {
                    this.MusteriIDField = value;
                    this.RaisePropertyChanged("MusteriID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalSystemApp.WinUI.AracServiceReference.MusterilerDTO MusterilerDTO {
            get {
                return this.MusterilerDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.MusterilerDTOField, value) != true)) {
                    this.MusterilerDTOField = value;
                    this.RaisePropertyChanged("MusterilerDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float SonKm {
            get {
                return this.SonKmField;
            }
            set {
                if ((this.SonKmField.Equals(value) != true)) {
                    this.SonKmField = value;
                    this.RaisePropertyChanged("SonKm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TeslimTarihi {
            get {
                return this.TeslimTarihiField;
            }
            set {
                if ((this.TeslimTarihiField.Equals(value) != true)) {
                    this.TeslimTarihiField = value;
                    this.RaisePropertyChanged("TeslimTarihi");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SirketDTO", Namespace="http://schemas.datacontract.org/2004/07/CarRentalSystemApp.DTO")]
    [System.SerializableAttribute()]
    public partial class SirketDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AracSayisiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO[] AraclarDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalSystemApp.WinUI.AracServiceReference.CalisanlarDTO[] CalisanlarDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SehirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SirketIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ad {
            get {
                return this.AdField;
            }
            set {
                if ((object.ReferenceEquals(this.AdField, value) != true)) {
                    this.AdField = value;
                    this.RaisePropertyChanged("Ad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AracSayisi {
            get {
                return this.AracSayisiField;
            }
            set {
                if ((this.AracSayisiField.Equals(value) != true)) {
                    this.AracSayisiField = value;
                    this.RaisePropertyChanged("AracSayisi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO[] AraclarDTO {
            get {
                return this.AraclarDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.AraclarDTOField, value) != true)) {
                    this.AraclarDTOField = value;
                    this.RaisePropertyChanged("AraclarDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalSystemApp.WinUI.AracServiceReference.CalisanlarDTO[] CalisanlarDTO {
            get {
                return this.CalisanlarDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.CalisanlarDTOField, value) != true)) {
                    this.CalisanlarDTOField = value;
                    this.RaisePropertyChanged("CalisanlarDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puan {
            get {
                return this.PuanField;
            }
            set {
                if ((this.PuanField.Equals(value) != true)) {
                    this.PuanField = value;
                    this.RaisePropertyChanged("Puan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sehir {
            get {
                return this.SehirField;
            }
            set {
                if ((object.ReferenceEquals(this.SehirField, value) != true)) {
                    this.SehirField = value;
                    this.RaisePropertyChanged("Sehir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SirketID {
            get {
                return this.SirketIDField;
            }
            set {
                if ((this.SirketIDField.Equals(value) != true)) {
                    this.SirketIDField = value;
                    this.RaisePropertyChanged("SirketID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MusterilerDTO", Namespace="http://schemas.datacontract.org/2004/07/CarRentalSystemApp.DTO")]
    [System.SerializableAttribute()]
    public partial class MusterilerDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EhliyetYasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalSystemApp.WinUI.AracServiceReference.KiralikBilgiDTO[] KiralikBilgiDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MusteriIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyisimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurucuYasiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TelNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EhliyetYasi {
            get {
                return this.EhliyetYasiField;
            }
            set {
                if ((this.EhliyetYasiField.Equals(value) != true)) {
                    this.EhliyetYasiField = value;
                    this.RaisePropertyChanged("EhliyetYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isim {
            get {
                return this.IsimField;
            }
            set {
                if ((object.ReferenceEquals(this.IsimField, value) != true)) {
                    this.IsimField = value;
                    this.RaisePropertyChanged("Isim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalSystemApp.WinUI.AracServiceReference.KiralikBilgiDTO[] KiralikBilgiDTO {
            get {
                return this.KiralikBilgiDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.KiralikBilgiDTOField, value) != true)) {
                    this.KiralikBilgiDTOField = value;
                    this.RaisePropertyChanged("KiralikBilgiDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MusteriID {
            get {
                return this.MusteriIDField;
            }
            set {
                if ((this.MusteriIDField.Equals(value) != true)) {
                    this.MusteriIDField = value;
                    this.RaisePropertyChanged("MusteriID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyisim {
            get {
                return this.SoyisimField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyisimField, value) != true)) {
                    this.SoyisimField = value;
                    this.RaisePropertyChanged("Soyisim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurucuYasi {
            get {
                return this.SurucuYasiField;
            }
            set {
                if ((this.SurucuYasiField.Equals(value) != true)) {
                    this.SurucuYasiField = value;
                    this.RaisePropertyChanged("SurucuYasi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TelNo {
            get {
                return this.TelNoField;
            }
            set {
                if ((this.TelNoField.Equals(value) != true)) {
                    this.TelNoField = value;
                    this.RaisePropertyChanged("TelNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CalisanlarDTO", Namespace="http://schemas.datacontract.org/2004/07/CarRentalSystemApp.DTO")]
    [System.SerializableAttribute()]
    public partial class CalisanlarDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CalisanIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IsimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KullaniciAdiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SifreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarRentalSystemApp.WinUI.AracServiceReference.SirketDTO SirketDTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SirketIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SoyisimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long TelNoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres {
            get {
                return this.AdresField;
            }
            set {
                if ((object.ReferenceEquals(this.AdresField, value) != true)) {
                    this.AdresField = value;
                    this.RaisePropertyChanged("Adres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CalisanID {
            get {
                return this.CalisanIDField;
            }
            set {
                if ((this.CalisanIDField.Equals(value) != true)) {
                    this.CalisanIDField = value;
                    this.RaisePropertyChanged("CalisanID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Isim {
            get {
                return this.IsimField;
            }
            set {
                if ((object.ReferenceEquals(this.IsimField, value) != true)) {
                    this.IsimField = value;
                    this.RaisePropertyChanged("Isim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KullaniciAdi {
            get {
                return this.KullaniciAdiField;
            }
            set {
                if ((object.ReferenceEquals(this.KullaniciAdiField, value) != true)) {
                    this.KullaniciAdiField = value;
                    this.RaisePropertyChanged("KullaniciAdi");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sifre {
            get {
                return this.SifreField;
            }
            set {
                if ((object.ReferenceEquals(this.SifreField, value) != true)) {
                    this.SifreField = value;
                    this.RaisePropertyChanged("Sifre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarRentalSystemApp.WinUI.AracServiceReference.SirketDTO SirketDTO {
            get {
                return this.SirketDTOField;
            }
            set {
                if ((object.ReferenceEquals(this.SirketDTOField, value) != true)) {
                    this.SirketDTOField = value;
                    this.RaisePropertyChanged("SirketDTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SirketID {
            get {
                return this.SirketIDField;
            }
            set {
                if ((this.SirketIDField.Equals(value) != true)) {
                    this.SirketIDField = value;
                    this.RaisePropertyChanged("SirketID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Soyisim {
            get {
                return this.SoyisimField;
            }
            set {
                if ((object.ReferenceEquals(this.SoyisimField, value) != true)) {
                    this.SoyisimField = value;
                    this.RaisePropertyChanged("Soyisim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long TelNo {
            get {
                return this.TelNoField;
            }
            set {
                if ((this.TelNoField.Equals(value) != true)) {
                    this.TelNoField = value;
                    this.RaisePropertyChanged("TelNo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AracServiceReference.IAracService")]
    public interface IAracService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_AraclarDTO/Listele", ReplyAction="http://tempuri.org/IServiceBaseOf_AraclarDTO/ListeleResponse")]
        CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO[] Listele();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_AraclarDTO/Listele", ReplyAction="http://tempuri.org/IServiceBaseOf_AraclarDTO/ListeleResponse")]
        System.Threading.Tasks.Task<CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO[]> ListeleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_AraclarDTO/Ekle", ReplyAction="http://tempuri.org/IServiceBaseOf_AraclarDTO/EkleResponse")]
        bool Ekle(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_AraclarDTO/Ekle", ReplyAction="http://tempuri.org/IServiceBaseOf_AraclarDTO/EkleResponse")]
        System.Threading.Tasks.Task<bool> EkleAsync(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_AraclarDTO/Güncelle", ReplyAction="http://tempuri.org/IServiceBaseOf_AraclarDTO/GüncelleResponse")]
        bool Güncelle(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_AraclarDTO/Güncelle", ReplyAction="http://tempuri.org/IServiceBaseOf_AraclarDTO/GüncelleResponse")]
        System.Threading.Tasks.Task<bool> GüncelleAsync(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_AraclarDTO/Sil", ReplyAction="http://tempuri.org/IServiceBaseOf_AraclarDTO/SilResponse")]
        bool Sil(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBaseOf_AraclarDTO/Sil", ReplyAction="http://tempuri.org/IServiceBaseOf_AraclarDTO/SilResponse")]
        System.Threading.Tasks.Task<bool> SilAsync(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAracServiceChannel : CarRentalSystemApp.WinUI.AracServiceReference.IAracService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AracServiceClient : System.ServiceModel.ClientBase<CarRentalSystemApp.WinUI.AracServiceReference.IAracService>, CarRentalSystemApp.WinUI.AracServiceReference.IAracService {
        
        public AracServiceClient() {
        }
        
        public AracServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AracServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AracServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO[] Listele() {
            return base.Channel.Listele();
        }
        
        public System.Threading.Tasks.Task<CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO[]> ListeleAsync() {
            return base.Channel.ListeleAsync();
        }
        
        public bool Ekle(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity) {
            return base.Channel.Ekle(entity);
        }
        
        public System.Threading.Tasks.Task<bool> EkleAsync(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity) {
            return base.Channel.EkleAsync(entity);
        }
        
        public bool Güncelle(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity) {
            return base.Channel.Güncelle(entity);
        }
        
        public System.Threading.Tasks.Task<bool> GüncelleAsync(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity) {
            return base.Channel.GüncelleAsync(entity);
        }
        
        public bool Sil(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity) {
            return base.Channel.Sil(entity);
        }
        
        public System.Threading.Tasks.Task<bool> SilAsync(CarRentalSystemApp.WinUI.AracServiceReference.AraclarDTO entity) {
            return base.Channel.SilAsync(entity);
        }
    }
}
